id: P003078
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 2021-12-17 10:38:58.843071
source_metadata:
  id: bdr:W1KG3819
  title: དཔལ་དུས་ཀྱི་འཁོར་ལོའི་ཆོ་ག་མཁས་གྲུབ་ཞལ་ལུང་
  author: ''
  volumes:
    752c7e4ef90145bd9b3e05566535667b:
      image_group_id: I1KG3865
      title: ''
      volume_number: 1
      total_pages: 652
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
