id: P003078
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG3819
  title: དཔལ་དུས་ཀྱི་འཁོར་ལོའི་ཆོ་ག་མཁས་གྲུབ་ཞལ་ལུང་
  author: ''
  volumes:
    752c7e4ef90145bd9b3e05566535667b:
      image_group_id: I1KG3865
      title: ''
      volume_number: 1
      total_pages: 652
